Patches produced by linkgit:git-format-patch[1] or
linkgit:git-send-email[1] are inline. This means that the output of
these two commands can lead to a different commit message when applied
with linkgit:git-am[1]. It can also mean that the patch is not applied
correctly.

The commit message might contain a three-dash line (`---`) which was
perhaps meant to be a thematic break. That means that the commit message
will be cut short. The presence of a line starting with "Index: " can
cause the patch not to be found, giving an error about an empty patch.

Furthermore, the presence of an unindented diff in the commit message
will not only cut the message short but cause that very diff to be
applied, along with the patch in the patch section. The commit message
might for example have a diff in a GitHub MarkDown code fence:

----
```
diff ...
```
----

The solution for this is to indent the diff instead:

----
    diff ...
----

This loss of fidelity might be simple to notice if you are applying
patches directly from a mailbox. However, a commit authored long ago
might be applied in a different context, perhaps because many changes
are being integrated via patch files and the
linkgit:git-format-patch[1] format is trusted to import changes of a
Git origin.

One might want to use a general-purpose utility like patch(1) instead,
given these limitations. However, patch(1) will not only look for
unindented diffs (like linkgit:git-am[1]) but will try to apply indented
diffs as well.
