git-history(1)
==============

NAME
----
git-history - EXPERIMENTAL: Rewrite history of the current branch

SYNOPSIS
--------
[synopsis]
git history abort
git history continue
git history quit
git history drop <commit>
git history reorder <commit> (--before=<following-commit>|--after=<preceding-commit>)

DESCRIPTION
-----------

Rewrite history by rearranging or modifying specific commits in the
history.

This command is similar to linkgit:git-rebase[1] and uses the same
underlying machinery. You should use rebases if you either want to
reapply a range of commits onto a different base, or interactive rebases
if you want to edit a range of commits.

Note that this command does not (yet) work with histories that contain
merges. You should use linkgit:git-rebase[1] with the `--rebase-merges`
flag instead.

THIS COMMAND IS EXPERIMENTAL. THE BEHAVIOR MAY CHANGE.

COMMANDS
--------

This command requires a subcommand. Several subcommands are available to
rewrite history in different ways:

`drop <commit>`::
	Drop a commit from the history and reapply all children of that
	commit on top of the commit's parent. The commit that is to be
	dropped must be reachable from the currently checked-out commit.
+
Dropping the root commit converts the child of that commit into the new
root commit. It is invalid to drop a root commit that does not have any
child commits, as that would lead to an empty branch.

`reorder <commit> (--before=<following-commit>|--after=<preceding-commit>)`::
	Move the commit so that it becomes either the parent of
	<following-commit> or the child of <preceding-commit>. The commits must
	be related to one another and must be reachable from the current `HEAD`
	commit.

The following commands are used to manage an interrupted history-rewriting
operation:

`abort`::
	Abort the history-rewriting operation and reset HEAD to the original
	branch.

`continue`::
	Restart the history-rewriting process after having resolved a merge
	conflict.

`quit`::
	Abort the history-rewriting operation but `HEAD` is not reset back to
	the original branch. The index and working tree are also left unchanged
	as a result.

EXAMPLES
--------

Drop a commit from history
~~~~~~~~~~~~~~~~~~~~~~~~~~

----------
$ git log --oneline
2d4cd6d third
125a0f3 second
e098c27 first
$ git history drop HEAD~
$ git log
b1bc1bd third
e098c27 first
----------

Reorder a commit
~~~~~~~~~~~~~~~~

----------
$ git log --oneline
a978f73 fifth
57594ee fourth
04eb1c4 third
d535e30 second
bf7438d first
$ git history reorder :/fourth --before=:/second
$ git log --oneline
1610fe0 fifth
444f97d third
2f90797 second
b0ae659 fourth
bf7438d first
$ git history reorder :/fourth --after=:/second
$ git log --oneline
c48729d fifth
f44a46e third
26693b8 fourth
8cb4171 second
bf7438d first
----------

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/sequencer.adoc[]

GIT
---
Part of the linkgit:git[1] suite
